version: '1.0'

services:
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx:delegated
      - ./src:/var/www/html:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      local-net:
        aliases:
          - web.local
          - localhost
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      local-net:
        aliases:
          - web.local
          - localhost

networks:
  local-net:
    driver: bridge